services:
  metaterminal-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-example
    volumes:
      - ./application:/usr/server/application
      - ./node_modules:/usr/server/node_modules
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    restart: always
    env_file:
      - .env

networks:
  default:
    name: metaterminal-api-network
