services:
  api:
    build:
      args:
        NODE_ENV: development
    ports:
      - 9229:9229
      - 8000:8000
    command: npm run dev
    environment:
      NODE_ENV: development
      NODE_OPTIONS: ''
    volumes:
      - ./application:/usr/server/application
      - ./log:/usr/server/log
      - ./node_modules:/usr/server/node_modules
