services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --max-old-space-size=2560
    volumes:
      - ./log:/usr/server/log
      - ./fixed/impress/lib/application.js:/usr/server/node_modules/impress/lib/application.js:ro
      - ./fixed/impress/lib/worker.js:/usr/server/node_modules/impress/lib/worker.js:ro
      - ./fixed/metacom/lib/server.js:/usr/server/node_modules/metacom/lib/server.js:ro
    networks:
      ptfin-backend:
        aliases:
          - metaterminal.ptfin.local

networks:
  ptfin-backend:
    external: true
    name: ptfin-backend
