services:
  metaterminal:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --max-old-space-size=2560
    volumes:
      - ./log:/usr/server/log
    networks:
      ptfin-backend:
        aliases:
          - metaterminal.ptfin.local

networks:
  ptfin-backend:
    external: true
    name: ptfin-backend
