services:
  metaterminal:
    build:
      context: /var/www/metaterminal
      dockerfile: Dockerfile
    container_name: metaterminal
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --max-old-space-size=2560
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: "6379"
    volumes:
      - ./log:/usr/server/log
